### ISSUE TITLE
PyPI sdist setup.py fails

### ISSUE THREAD

**Issue by jayvdb** [T8T9/paddle1to2#25]
```py
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    with open('requirements.txt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by T8T9** [comment]
@jayvdb paddle_upgrade_tool only support Python >=3.5.4. Give it a try please.

**Comment by jayvdb** [comment]
The problem is not fixed.  https://files.pythonhosted.org/packages/c0/24/f2a4dbeb8b4db7a32645a22a1f162a45ed11b178082d4ebbc6f8aaaa4481/paddle_upgrade_tool-0.0.26.tar.gz does not contain `requirements.txt`, but setup.py requires it.

**Comment by jayvdb** [comment]
ping @T8T9

**Comment by T8T9** [comment]
> The problem is not fixed. https://files.pythonhosted.org/packages/c0/24/f2a4dbeb8b4db7a32645a22a1f162a45ed11b178082d4ebbc6f8aaaa4481/paddle_upgrade_tool-0.0.26.tar.gz does not contain `requirements.txt`, but setup.py requires it.


The [binary distributed package](https://files.pythonhosted.org/packages/c0/f0/da112faf332137e84638f87bd5db6f2052ae0382f8881541f8e9f8a69f8c/paddle_upgrade_tool-0.0.26-py3-none-any.whl) doesn't need a "requirements.txt". The source distributed package has no "requirements.txt" because requirements.txt is empty. If you stick to installing from source code, clone this repo to your local machine, then follow this [tutorial](https://github.com/PaddlePaddle/paddle_upgrade_tool#install).

**Comment by jayvdb** [comment]
If you dont want to make the PyPI sdist functional, you shouldnt upload it to PyPI.
